baseURL = "https://sumeetsahu.github.io/"
languageCode = "en-us"
title = "Sumeet Sahu"
theme = "hugo-resume"

[params]
    firstName = "Sumeet"
    lastName = "Sahu"
    address = "New Delhi, India"
    phone = "0091-9963027920"
    contactNote = "Computer Scientist at Adobe"
    profileImage = "img/homepage_profile.jpg"
    email = "contactme@sumeetsahu.com"
    description = "Software Engineer with experience implementing architectural changes, adopting new technologies, creating proof-of-concept, influencing product requirements, implementing and reviewing changes, and mentoring team to implement best practices and to improve engineering efficiency."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQr = false

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/sumeetsahu/"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/sumeetsahu/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/sumeetsahu/"

[params.google.analytics]
    trackerID = "UA-152088779-1"
